sudo : required
services :
  - docker

before_install :
  - docker build -t mazzama/practice-docker-react -f Dockerfile.dev .

script :
  - docker run mazzama/practice-docker-react npm run test -- --coverage